name: "On pull request"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: run bicep plan
    env:
      GITHUB_TOKEN: ${{ github.token }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Bicep WhatIf - Resource Group
        id: bicep_rg
        uses: jf781/GHActions/bicep-deployment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deployment-scope: 'subscription'
          deployment-subscription: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          deployment-region: ${{ vars.AZURE_REGION }}
          deployment-template: 'resourceGropus/resourceGroups.bicep'
          deployment-parameters: 'paramFiles/resourceGroups.bicepparam'
          deployment-operation: 'whatIf'

      - name: Testing
        shell: bash
        run: |
          echo ${{ steps.bicep_rg.outputs }}

      - name: Bicep WhatIf - Resources
        uses: jf781/GHActions/bicep-deployment@main
        id: bicep_resources
        env:
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deployment-scope: 'resourceGroup'
          deployment-resource-group: 'demoRg'
          deployment-subscription: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          deployment-region: ${{ vars.AZURE_REGION }}
          deployment-template: 'resources/resources.bicep'
          deployment-parameters: 'paramFiles/resources.bicepparam'
          deployment-operation: 'whatIf'

