name: "On Push"

# on:
#   push:
#     branches-ignore:
#       - main
#     tags-ignore:
#       - "*"

on: push

permissions:
  contents: write
  pull-requests: write
  actions: write
  id-token: write
  security-events: write 

jobs:
  checkov-github-actions-scan:
    runs-on: ubuntu-latest
    name: workflow scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "github workflow actions scan"
        id: "github-workflow-actions-scan"
        uses: jf781/GHActions/github-workflow-scan@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

  iac-static-analysis:
    runs-on: ubuntu-latest
    name: checkov static analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "github workflow static analysis"
        id: "github-workflow-static-analysis"
        uses: jf781/GHActions/iac-static-analysis@main
        with:
          config-file: tests/checkov/config.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

  bicep-linting:
    runs-on: ubuntu-latest
    name: bicep linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Bicep Linting"
        id: "github-workflow-iac-linting"
        uses: jf781/GHActions/bicep-linter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false
