name: "On Push"

on:
  push:
    # branches-ignore:
    #   - main
    # tags-ignore:
    #   - "*"

permissions:
  contents: write
  pull-requests: write


jobs:
  checkov-github-actions-scan:
    runs-on: ubuntu-latest
    name: workflow scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "github workflow static analysis"
        id: "github-workflow-static-analysis"
        uses: jf781/GHActions/github-workflow-scan@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

  iac-static-analysis:
    runs-on: ubuntu-latest
    name: workflow scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "github workflow static analysis"
        id: "github-workflow-static-analysis"
        uses: jf781/GHActions/iac-static-analysis@main
        with:
          config-file: tests/checkov/config.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false