name: "On Push"

# on:
#   push:
#     branches-ignore:
#       - main
#     tags-ignore:
#       - "*"

on: push

permissions:
  contents: write
  pull-requests: write
  actions: write
  id-token: write
  security-events: write 

jobs:
  checkov-github-actions-scan:
    runs-on: ubuntu-latest
    name: workflow scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "github workflow actions scan"
        id: "github-workflow-actions-scan"
        uses: jf781/GHActions/github-workflow-scan@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

  iac-static-analysis:
    runs-on: ubuntu-latest
    name: checkov static analysis
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "github workflow static analysis"
        id: "github-workflow-static-analysis"
        uses: jf781/GHActions/iac-static-analysis@main
        with:
          config-file: tests/checkov/config.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

  bicep-linting:
    runs-on: ubuntu-latest
    name: bicep linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Bicep Linting"
        id: "github-workflow-iac-linting"
        uses: jf781/GHActions/bicep-linter@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: false

  bicep-validation-resource-groups:
    runs-on: ubuntu-latest
    name: bicep validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Parse Parameters File
        shell: pwsh
        id: parse_parameters
        run: |
          $params = ((az bicep build-params --file paramFiles/resourceGroups.bicepparam --stdout | ConvertFrom-Json).parametersJson | ConvertFrom-Json)
          $location = $params.parameters.rg.value.location
          $resource_group_name = $params.parameters.rg.value.name
          echo "location is $location"
          echo "resource_group_name is $resource_group_name"
          echo "location=$location" >> $env:GITHUB_OUTPUT
          echo "resource_group_name=$resource_group_name" >> $env:GITHUB_OUTPUT

      - name: Bicep Validation - Resource Group
        id: bicep_resource_group
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: 'validate'
          name: " ${{ steps.parse_parameters.outputs.location }}-${{ steps.parse_parameters.outputs.resource_group_name }}"
          scope: subscription
          location: ${{ steps.parse_parameters.outputs.location }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: 'resourceGropus/resourceGroups.bicep'
          parameters-file: 'paramFiles/resourceGroups.bicepparam'

  bicep-validation-resources:
    runs-on: ubuntu-latest
    name: bicep validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Parse Parameters File
        shell: pwsh
        id: parse_parameters
        run: |
          $params = ((az bicep build-params --file paramFiles/resourceGroups.bicepparam --stdout | ConvertFrom-Json).parametersJson | ConvertFrom-Json)
          $location = $params.parameters.rg.value.location
          $resource_group_name = $params.parameters.rg.value.name
          echo "location is $location"
          echo "resource_group_name is $resource_group_name"
          echo "location=$location" >> $env:GITHUB_OUTPUT
          echo "resource_group_name=$resource_group_name" >> $env:GITHUB_OUTPUT

      - name: Bicep Validation - Resource Group
        id: bicep_resource_group
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: 'validate'
          name: " ${{ steps.parse_parameters.outputs.location }}-${{ steps.parse_parameters.outputs.resource_group_name }}"
          scope: subscription
          location: ${{ steps.parse_parameters.outputs.location }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          template-file: 'resourceGropus/resourceGroups.bicep'
          parameters-file: 'paramFiles/resourceGroups.bicepparam'

      - name: Bicep Validation - Resources
        id: bicep_resources
        uses: azure/bicep-deploy@v2
        with:
          type: deployment
          operation: 'validate'
          name: " ${{ steps.parse_parameters.outputs.location }}-${{ steps.parse_parameters.outputs.resource_group_name }}-resources"
          scope: resourceGroup
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resource-group-name: ${{ steps.parse_parameters.outputs.resource_group_name }}
          template-file: 'resources/resources.bicep'
          parameters-file: 'paramFiles/resources.bicepparam'
