name: "On pull request"

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    name: run bicep plan
    env:
      GITHUB_TOKEN: ${{ github.token }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Bicep WhatIf - Resource Group
        id: bicep_rg
        uses: jf781/GHActions/bicep-deployment@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deployment-scope: 'subscription'
          deployment-subscription: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          deployment-region: ${{ vars.AZURE_REGION }}
          deployment-template: 'resourceGropus/resourceGroups.bicep'
          deployment-parameters: 'paramFiles/resourceGroups.bicepparam'
          deployment-operation: 'whatIf'

      - name: Parse Parameters File
        shell: pwsh
        id: parse_parameters
        run: |
          $params = ((az bicep build-params --file paramFiles/resourceGroups.bicepparam --stdout | ConvertFrom-Json).parametersJson | ConvertFrom-Json)
          $location = $params.parameters.rg.value.location
          $resource_group_name = $params.parameters.rg.value.name
          echo "location is $location"
          echo "resource_group_name is $resource_group_name"
          echo "location=$location" >> $env:GITHUB_OUTPUT
          echo "resource_group_name=$resource_group_name" >> $env:GITHUB_OUTPUT

      - name: Create Temp Resource Group
        shell: bash
        id: create_temp_rg
        run: |
          if az group exists --name ${{ steps.parse_parameters.outputs.resource_group_name }}; then
            echo "Resource group ${{ steps.parse_parameters.outputs.resource_group_name }} already exists"
            echo "resource_group_exists=true" >> $GITHUB_OUTPUT
          else
            az group create --name ${{ steps.parse_parameters.outputs.resource_group_name }} --location ${{ steps.parse_parameters.outputs.location }}
            echo "resource_group_exists=false" >> $GITHUB_OUTPUT
          fi


      - name: Bicep WhatIf - Resources
        uses: jf781/GHActions/bicep-deployment@main
        id: bicep_resources
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
          deployment-scope: 'resourceGroup'
          deployment-resource-group: ${{ steps.parse_parameters.outputs.resource_group_name }}
          deployment-subscription: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          deployment-region: ${{ steps.parse_parameters.outputs.location }}
          deployment-template: 'resources/resources.bicep'
          deployment-parameters: 'paramFiles/resources.bicepparam'
          deployment-operation: 'whatIf'

      - name: Remove Temp Resource Group
        shell: bash
        id: remove_temp_rg
        run: |
          if [[ ${{ steps.create_temp_rg.outputs.resource_group_exists}} ]]; then
            echo "No changes, pre-defined resource group. Skipping deletion"
          else
            az group delete --name ${{ steps.parse_parameters.outputs.resource_group_name }} --location ${{ steps.parse_parameters.outputs.location }}
            echo "Removing resource group ${{ steps.parse_parameters.outputs.resource_group_name }}"
          fi